# Lista de Exercícios de Numpy

Deverá ser entrege até **11/02/2023** por meio do github que foi informado por vocês no [formulário](https://forms.office.com/r/YV12vEXGYF) respondido na aula de 01/02.

A entrega pela github é parte da avaliação.

## Questão 1

Crie um array 100 com valores aleatórios e ache os valores máximo e mínimo

In [ ]:
import numpy as np

# cria um array com 100 valores aleatórios entre 0 e 1, sendo o 0 inclusivo e o 1 exclusivo
array_100_valores = np.random.rand(100)

# cria um array com 'n' valores aleatórios, apenas inteiros, entre um intervalo especificado: np.random.randint(x, y, n), onde:
          # x é o valor inicial (inclusivo)
          # y é o último valor (exclusivo)
          # n é o número de valores no array
array_100_valores_inteiros = np.random.randint(0,100,100)

# encontra o valor máximo e mínimo do primeiro array (valores entre 0 e 1)
valor_max_primeiro_array = array_100_valores.max()
valor_min_primeiro_array = array_100_valores.min()

# encontra o valor máximo e mínimo do segundo array (entre 0 e 100)
valor_max_segundo_array = array_100_valores_inteiros.max()
valor_min_segundo_array = array_100_valores_inteiros.min()

print(f'No primeiro array, o valor máximo é = {valor_max_primeiro_array} e o valor mínimo é = {valor_min_primeiro_array}.')
print(f'No segundo array, o valor máximo é = {valor_max_segundo_array} e o valor mínimo é = {valor_min_segundo_array}.')

No primeiro array, o valor máximo é = 0.9803603146955018 e o valor mínimo é = 0.02230450417059615.
No segundo array, o valor máximo é = 98 e o valor mínimo é = 1.


## Questão 2
Em Geometria Analítica, um **vetor** é uma quantidade que pode ser definida por um énuplo (uma sequência ordenada de *n* elementos) em que cada elemento representa a intensidade do vetor na direção especificada pela i-ésima componente desta sequência. 

Quando pensamos em duas dimensões, por exemplo, o vetor $R = (b,a)$ define, geometricamente, a entidade representada na figura abaixo, com componentes nos eixos x e y usuais.

<img src = "https://static.todamateria.com.br/upload/im/ag/image-721.jpg?auto_optimize=low" />

O **módulo** deste vetor, também chamado de intensidade, está geometricamente relacionado ao seu comprimento, e pode ser calculado diretamente pelas suas componentes, por meio de uma operação conhecida como **produto escalar** do vetor com ele mesmo. O módulo quadrático é expresso, desta forma, por:

$|A|^2 = \vec{A} \cdot \vec{A}$

Por outro lado, o produto escalar entre dois vetores $A = (a_{x}, a_{y})$ e $B = (b_{x}, b_{y})$ é dado por:

$\vec{A} \cdot \vec{B} = a_{x} \times b_{x} + a_{y} \times b_{y}$ (e esta definição vale para qualquer que seja a dimensão do vetor).

O módulo quadrático de um vetor é, portanto:

$|A|² = a_{x}^2 + b_{x}^2$.

Dado o exposto acima, escreva uma função que retorne o módulo de um vetor n-dimensional qualquer.

In [ ]:
import numpy as np

# valor aleatório, de 0 a 10, para definir o tamanho 'n' do vetor
qntd_de_termos_do_vetor = np.random.randint(10) 

# vetor com tamanho 'n', aleatório, de valores inteiros de 0 a 100
vetor_aleatorio = np.random.randint(0, 100, qntd_de_termos_do_vetor)

def calcula_modulo_vetor(x,y):
  soma = 0
  for i in range(x):
    soma += y[i]**2
  return np.sqrt(soma)

# chama a função que calcula o módulo do vetor e armazena na variável chamada 'modulo'
modulo = calcula_modulo_vetor(qntd_de_termos_do_vetor, vetor_aleatorio)


print(f'O vetor é: v = {vetor_aleatorio}.')
print(f'O módulo do vetor é: |v| = {modulo}.')

O vetor é: v = [12  4 92 95 19 56 93 63].
O módulo do vetor é: |v| = 183.74982993189408.


## Questão 3

Em uma **análise de regressão**, usualmente estamos interessados em descrever relações entre variáveis de um dado conjunto de dados por meio de uma **função** que descreva, o tanto quanto possível, estas relações.

Por exemplo, no gráfico abaixo, os pontos vermelhos relacionam as medidas das duas variáveis sendo avaliadas (nos eixos x e y); e a linha azul aproxima a relação entre elas por uma função linear.

![Normdist_regression.png](https://miro.medium.com/v2/resize:fit:786/format:webp/1*LEmBCYAttxS6uI6rEyPLMQ.png)

É possível ver que nem todos os pontos obedecem exatamente à relação ditada pela reta (isto é, há pontos que não estão exatamente "sobre a reta"; mas, sim, ligeraimente acima, ou abaixo, dela). Isto, contudo, é esperado em um modelo de regressão, por inúmeras fontes de incerteza associadas às medições.

Uma das métricas que utilizamos para avaliar a qualidade de uma regressão é o **erro quadrático médio (EQM)**, que mensura a diferença total entre cada predição da regressão ($y_{prediction}$; que no nosso caso seriam os valores de y para a reta azul) com o valor real de cada i-ésima medida ($y_{i}$; que no nosso caso seriam as coordenadas y para cada ponto vermelho do gráfico). O EQM pode ser definido como:

$EQM = \frac{1}{n}\sum_{i=1}^{n}(y_{prediction} - y_{i})^2$.

Isto posto, escreva uma função que calcule o EQM recebendo, como entrada, os vetores $y_{prediction}$ e $y_{i}$. Por exemplo, digamos que sua função se chame *calculate_eqm*, ela deve operar da seguinte forma:

In [ ]:
# dados dois arrays quaisquer de mesmo tamanho, a função deve retornar o EQM
# y_prediction = np.array([1,2,3])
# y_i = np.array([0,0,3])
# calculate_eqm(y_prediction,y_i)
# >>> 1.6666666663

In [ ]:
import numpy as np

# gera uma quantidade para o tamanho dos array's
n = np.random.randint(10) 

# array com 'n' valores entre 0 e 10
y_predicao = np.random.randint(0,10,n)

# array com 'n' valores entre 0 e 10
y_real = np.random.randint(0,10,n)

def calcula_eqm(x,y,n): # x=y_predicao; y=y_real
  soma = 0
  for i in range(n):
    soma += (y_predicao[i] - y_real[i]) ** 2
  return soma / n

# executa a função para calcular o valor do EQM
eqm = calcula_eqm(y_predicao,y_real,n)

print(f'Os valores de predição são: y_predicao = {y_predicao}.')
print(f'Os valores reais são: y_real = {y_real}.')
print(f'O valor do EQM é = {eqm}.')

Os valores de predição são: y_predicao = [4 7 3 6 5 7].
Os valores reais são: y_real = [8 5 8 4 8 8].
O valor do EQM é = 9.833333333333334.


## Questão 4

Crie um array 2D (bidimensional) com 1 na borda e 0 dentro

In [ ]:
import numpy as np

# gera uma quantidade para o tamanho do array
n = np.random.randint(10) 

# cria um array de zeros com 'n'-linhas e 'n'-colunas
array_de_zeros = np.zeros((n,n),dtype=np.int64)

if n != 0:
  # substitui a primeira linha (borda de cima)
  array_de_zeros[0,:] = 1

  # substitiu a última linha (borda de baixo)
  array_de_zeros[-1,:] = 1

  # substitiu a primeira coluna (borda esquerda)
  array_de_zeros[:,0] = 1

  # substitiu a última coluna (borda direita)
  array_de_zeros[:,-1] = 1

  print(f'Array de dimensão {n}x{n}: \n{array_de_zeros}.')
else:
  print(f'Array vazio: {array_de_zeros}.')


Array de dimensão 7x7: 
[[1 1 1 1 1 1 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 1 1 1 1 1 1]].


## Questão 5

Como adicionar uma borda de 0's ao redor de um array 2D (bidimensional) existente

In [ ]:
import numpy as np

# gera uma quantidade para o tamanho do array
n = np.random.randint(10) 

# array com tamanho 'n', aleatório, de valores inteiros de 0 a 100
array_aleatorio = np.random.randint(0,100,(n,n))

# array com tamanho 'n+1' de zeros
array_aleatorio_maior = np.zeros((n+1,n+1),dtype=np.int64)

# adiciona o array de números aleatórios dentro do array de zeros, deixando a primeira linha e a primeira coluna com os valores 0
array_aleatorio_maior[1:,1:] = array_aleatorio

# adiciona uma coluna de zeros à direita (borda direita)
array_aleatorio_maior = np.append(array_aleatorio_maior,np.zeros((n+1,1),dtype=np.int64),axis=1)

# adiciona uma linha de zeros no final (borda de baixo)
array_aleatorio_maior = np.append(array_aleatorio_maior,np.zeros((1,n+2),dtype=np.int64),axis=0)

print(f'O array inicial é: \n dim.: {n}x{n} \n {array_aleatorio}. \n')
print(f'O array final, com borda de zeros, é: \n dim.: {n+2}x{n+2} \n {array_aleatorio_maior}.')

O array inicial é: 
 dim.: 1x1 
 [[30]]. 

O array final, com borda de zeros, é: 
 dim.: 3x3 
 [[ 0  0  0]
 [ 0 30  0]
 [ 0  0  0]].


## Questão 6

 A eletroencefalografia (EEG) é uma técnica que mensura potenciais elétricos cerebrais em diversas regiões do escalpo do paciente. Suponha que você recebeu um conjunto de dados na forma de uma matriz de 64 x 512 elementos, em que cada linha contém o sinal gravado em um dos **eletrodos** espalhados pelo escalpo em um exame de EEG, e cada coluna contém um valor de potencial elétrico, em microvolts. 

Como o sinal de EEG é muito suscetível a ruídos externos (interferências na qualidade do sinal), uma operação comum para atenuar a interferência no sinal consiste em tirar a média do potencial elétrico de todos os eletrodos, e subtrair este valor de cada um deles. Isto atenua fontes de ruído ao sinal comuns a todos os eletrodos. Em termos matemáticos, o sinal processado por esta operação, $X_{e,i}$ para cada eletrodo (e) e amostra (i), é dado por:

$X_{e,i} = \hat{X_{e,i}} - \frac{1}{N}\sum_{e=1}^{N}\hat{X_{e,i}}$,

em que $\hat{X_{e,i}}$ representa o sinal original (ou seja, é a matriz de entrada de 64 x 512 elementos), e $N$ indica o total de eletrodos.

Com o exposto acima, escreva uma função que retorne uma matriz com os sinais de EEG processados conforme a operação mencionada. Sua função deve operar conforme o exemplo abaixo.

In [ ]:
# import numpy as np
# vamos supor uma matriz de entrada gerada por dados aleatórios
# X = np.random.randn(64,512)
# X.shape # apenas para verificar as dimensões
# >>> (64, 512)

# a função deve executar a operação equacionada anteriormente, retornando uma nova matriz
# X_processado = process_EEG_signal(X)
# X_processado.shape
# >>> (64, 512)

# Somando as diferenças entre cada elemento das duas matrizes, apenas para ilustrar que elas não são iguais
# (X_processado - X).sum()
# >>> -53.08727366483029

# Visualizando as matrizes, para verificar uma vez mais que, de fato, os elementos são diferentes
# X
# >>> array([[ 0.29305925,  0.89663038, -0.61032202, ..., -0.88086364,
#             -0.8818789 ,  0.51260497],
#            [-0.01274415,  1.05439522,  0.47958092, ..., -2.15387924,
#              0.70721168,  0.97029889],
#            [ 1.09478371, -0.16120847,  1.58400361, ...,  0.20981813,
#              2.17373837,  0.94032162],
#            ...,
#            [-0.45294842, -2.28939505,  1.10111998, ...,  1.63581703,
#             -0.39394924, -1.13400723],
#            [-0.22669886,  0.25413429, -1.17870637, ..., -0.09509442,
#              0.90733806,  0.37999411],
#            [ 0.15476933, -0.03654717, -1.09982762, ...,  0.67600047,
#             -0.84533328, -0.56433144]])

# Matriz após o processamento descrito no enunciado
# X_processado
# >>> array([[ 0.36713022,  0.85772513, -0.54902169, ..., -0.85626087,
#             -0.97611435,  0.51718998],
#            [ 0.06132682,  1.01548997,  0.54088126, ..., -2.12927647,
#              0.61297623,  0.97488389],
#            [ 1.16885469, -0.20011372,  1.64530394, ...,  0.23442091,
#              2.07950292,  0.94490663],
#            ...,
#            [-0.37887744, -2.3283003 ,  1.16242031, ...,  1.6604198 ,
#             -0.4881847 , -1.12942223],
#            [-0.15262788,  0.21522904, -1.11740604, ..., -0.07049164,
#              0.81310261,  0.38457911],
#            [ 0.22884031, -0.07545242, -1.03852729, ...,  0.70060324,
#             -0.93956874, -0.55974643]])

In [ ]:
import numpy as np

# criação do array de 64x512 de dados aleatórios
dados_aleatorios = np.random.randn(64,512)

def processa_dados_eeg(dados_aleatorios):
  # calcula a média do array
  media = dados_aleatorios.mean()

  # subtrai a média de cada valor dentro do array inicial e cria um novo array com os dados processados
  dados_aleatorios_processados = dados_aleatorios - media
  
  return dados_aleatorios_processados, media

# o 'return' da função fornece uma tupla, na qual a média é o segundo termo (índice = 1)
print(f'A Média do potencial elétrico dos diodos é = {processa_dados_eeg(dados_aleatorios)[1]}. \n') 

print(f'A matriz inicial é: \n {dados_aleatorios}. \n')
print(f'A matriz processada é: \n {processa_dados_eeg(dados_aleatorios)[0]}.')

## Questão 7

Em estatística, um **outlier** é um valor que destoa consideravelmente da distribuição à qual está associado. Um dos critérios para idenficar outliers consiste em encontrar a **distância interquantil** (IQR), ou seja, a diferença entre o terceiro (Q3) e o primeiro quartis (Q1) da distribuição, e tomar como outliers todos os pontos abaixo de 1.5*IQR - Q1, ou acima de 1.5*IQR + Q3.

<img src = "https://blog.curso-r.com/images/posts/banner/outlier.webp" />

Escreva uma função que, dada uma matriz de dados de entrada de dimensões $N_{observações} \times N_{features}$ retorne três requisitos: 
- uma matriz booleana indicando a existência de outliers nos dados de entrada;
- a quantidade de outliers
- quem são os outliers (os valores).

**Algumas definições:**
- um *quantil* divide a distribuição, após ordenados os pontos, segundo algum ponto de corte;
- o **primeiro quartil** é o ponto para o qual 25 % dos valores da distribuição estão abaixo dele;
- o **terceiro quartil** é o ponto para o qual 75 % dos valores da distribuição estão abaixo dele.

Pode ser útil consultar a função **numpy.quantile**.

Exemplo de operação da função:

In [ ]:
'''
# Geremos um conjunto de dados qualquer
X = np.random.randn(300,15)
>>> array([[ 1.38099939, -1.00625541,  0.00968184, ..., -0.20784191,
             0.36232481, -0.4071473 ],
           [ 0.64009538, -0.47358915,  1.27057446, ...,  0.13400926,
            -0.82165675, -2.92180194],
           [-1.17075282, -0.084285  , -0.93022482, ...,  0.75297628,
             0.23420238, -0.01112133],
           ...,
           [-1.33355822, -1.94712603, -0.83136148, ..., -0.36718705,
             0.87680528,  0.56366331],
           [ 0.39996864,  0.96285484, -0.70921429, ...,  0.15784522,
             0.9663939 ,  1.50170879],
           [ 0.69004696,  0.1588939 ,  0.04541013, ..., -0.74624076,
            -0.93105604,  1.16555654]])

# identificamos os requisitos com nossa com nossa função "locate_outliers"
is_outlier, outliers_count, outliers = locate_outliers(X)

is_outlier
>>> array([[False, False, False, ..., False, False, False],
           [False, False, False, ..., False, False, False],
           [False, False, False, ..., False, False, False],
           ...,
           [False, False, False, ..., False, False, False],
           [False, False, False, ..., False, False, False],
           [False, False, False, ..., False, False, False]])

outliers_count
>>> 44

outliers
>>> array([-2.67240384,  3.00270904,  3.62317101,  3.18867865,  2.55581522,
           -2.82091429,  2.8757892 ,  2.70666036,  3.19514999, -3.40550318,
           -3.39825827,  2.6727295 ,  2.54498296, -2.69447104,  3.19521603,
            2.66372172, -2.77444948,  2.77421152,  2.69992869, -2.84831109,
           -2.83695779, -2.45908227,  3.07802106,  2.89314015, -2.68574682,
           -2.85019494,  2.43399574,  2.44291266, -2.92595937, -2.95911074,
           -3.03966003,  2.77543068, -2.67368414, -2.79965402, -3.0501958 ,
           -2.5437387 ,  3.08550649, -3.17666255, -3.05795476, -3.09826467,
            3.1399469 ,  3.18141942,  2.90564257, -2.89505054])

'''

In [ ]:
import numpy as np

# gera um array aleatorio de tamanho especificado
array_aleatorio = np.random.randn(300,15)

# gera um array cópia do principal
array_copia = np.copy(array_aleatorio)

def localiza_outliers(array_aleatorio, array_copia):
  # retorna um escalar, referente ao quartil 25%
  quartil_25 = np.quantile(array_aleatorio, 0.25)

  # retorna um escalar, referente ao quartil 75%
  quartil_75 = np.quantile(array_aleatorio, 0.75)

  # cálculo da distância interquartil (iqr)
  iqr = quartil_75 - quartil_25

  # regras para considerar um valor como outlier
  regra_1 = quartil_25 - (1.5 * iqr)
  regra_2 = quartil_75 + (1.5 * iqr)

  # retorna um array de booleano dos valores outliers
  for i in range(0,300):
    for k in range(0,15):
      if ((array_aleatorio[i,k] < regra_1) or (array_aleatorio[i,k] > regra_2)):
        array_aleatorio[i,k] = 1
      else:
        array_aleatorio[i,k] = 0

  # retorna a quantidade de outliers na amostra np.count_nonzero()
  qntd_outlier = int(array_aleatorio.sum())

  # retorna um array com os valores dos outliers
  outliers =  array_copia[array_aleatorio == True]

  return array_aleatorio, qntd_outlier, outliers

array_bool, qntd_outlier, outliers = localiza_outliers(array_aleatorio, array_copia)

print(f'O array booleano com a indicação dos outliers é: \n {array_bool}. \n')
print(f'A quantidade de outliers no array é = {qntd_outlier}. \n')
print(f'Os outliers são: \n {outliers}. \n')

O array booleano com a indicação dos outliers é: 
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]. 

A quantidade de outliers no array é = 30. 

Os outliers são: 
 [-3.0317516  -2.68305098  2.98144142 -3.7432558   3.08002585  2.81460701
 -2.8154814  -2.68673612  3.02211929 -2.90788934 -2.82131795  2.78752786
 -2.65861427  2.9668474   3.11894296  3.05104863  3.46209739  2.79396516
 -2.74563756 -2.70641171 -2.91429425 -2.70768884  2.9252185   2.96182267
 -2.84466603  2.82252958 -3.10959684  2.77049751 -3.05165538 -3.27055933]. 



## Questão 8

Crie um vetor com valores que vão de 1 até 21 de dois em dois, a partir da função arange

In [ ]:
import numpy as np

# cria um vetor que possui valores de 1 a 21 (ambos inclusivos), pulando de 2 em 2
vetor = np.arange(1,23,2)

print(f'O vetor é: {vetor}.')

O vetor é: [ 1  3  5  7  9 11 13 15 17 19 21].


## Questão 9

Crie um array de 10 com valores aleatórios

In [ ]:
import numpy as np

# cria um array com 10 valores aleatórios entre 0 e 1 (exclusivo)
array_10_elementos = np.random.rand(10)

# cria um array com 10 valores aleatórios, considerando a "Distribuição Normal", onde a média dos valores é igual a zero e o desvio padrão é igual a 1
array_10_elementos_standard = np.random.randn(10)

# cria um array considerando a "Distribuição Uniforme Discreta" de valores, com tamanho e forma (size) especificado e com o valor máximo (exclusivo) especificado
array_10_elementos_discrete = np.random.randint(10,size=(2,5))

print(array_10_elementos, '\n')
print(array_10_elementos_standard, '\n')
print(array_10_elementos_discrete)

[0.67474267 0.1881713  0.09391418 0.2269079  0.39961547 0.31741738
 0.45306265 0.78530876 0.7380421  0.55462049] 

[ 0.09692747  1.93886484 -1.3658698  -0.33937761  1.96439005 -0.46625599
  0.2953062  -2.02031994  1.36876595  0.37790581] 

[[8 7 4 5 7]
 [7 8 3 3 1]]


## Questão 10

Em estatística, a normalização de uma distribuição de dados pode ser feita subtraindo o valor médio da distribuição de cada valor do conjunto de dados, dividindo o resultado pelo desvio-padrão da distribuição. Escreva uma função que normalize os dados recebidos por um array numpy qualquer, conforme descrito anteriormente.

In [ ]:
import numpy as np

def normaliza():
  # cria um array com 10 dados aleatórios
  dados = np.random.rand(10)

  # calcula a média da distribuição de dados
  media = np.mean(dados)

  # calcula o desvio padrão dos dados
  desvio = np.std(dados)

  # array com os dados subtraida a média
  dados_sub_media = dados - media

  # array com os dados_sub_media divididos pelo desvio padrão da distribuição total
  dados_final = dados_sub_media / desvio

  return dados, dados_sub_media, dados_final

dados, dados_sub_media, dados_final = normaliza()

print(f'A distribuição de dados original é: \n {dados}. \n')
print(f'A distribuição subtraída a média é: \n {dados_sub_media}. \n')
print(f'A distribuição normalizada (dividida pelo desvio padrão) é: \n {dados_final}.')

A distribuição de dados original é: 
 [0.85042011 0.66466341 0.1733007  0.11636233 0.76771671 0.34676736
 0.42620407 0.44951164 0.56562239 0.62624896]. 

A distribuição subtraída a média é: 
 [ 0.35173834  0.16598164 -0.32538107 -0.38231943  0.26903494 -0.15191441
 -0.0724777  -0.04917013  0.06694062  0.12756719]. 

A distribuição normalizada (dividida pelo desvio padrão) é: 
 [ 1.53191478  0.72289456 -1.4171218  -1.66510364  1.17171931 -0.66162798
 -0.3156598  -0.21414909  0.29154434  0.55558932].


## Questão 11

Escreva uma função em numpy que receba um array contendo notas de uma turma de 100 estudantes. Considere que a nota de aprovação da turma é 5.0. A função deve retornar, em um array numpy, nesta ordem:
- a média e o desvio-padrão das notas da turma;
- o número de notas maiores que 7.0;
- o número de reprovações da turma;
- a menor nota da turma;
- a maior nota da turma.

In [ ]:
import numpy as np

# cria um array com 100 valores (notas) aleatórias
notas = np.random.rand(100) * 10

def analisa_notas(notas):
  # calcula a média da distribuição
  media = np.mean(notas)

  # calcula o desvio padrão da distribuição
  desvio = np.std(notas)

  # retorna a quantidade de notas maiores que 7
  maior_7 = (notas > 7).sum()

  # retorna a quantidade de notas menores que 5
  reprovados = (notas < 5).sum()

  # retorna a maior nota (maior valor da distribuição)
  maior_nota = np.max(notas)

  # retorna a menor nota (menor valor da distribuição)
  menor_nota = np.min(notas)

  return media, desvio, maior_7, reprovados, maior_nota, menor_nota

resultado = np.array(analisa_notas(notas),dtype=np.float64)

print(resultado)

[ 4.79482939  2.84799848 28.         55.          9.97586227  0.06511913]
